### ISSUE TITLE
How do I support 'json.Marshal' 'time.now' 'fmt.xxx' in wasm writen in go 

### ISSUE THREAD

**Issue by wahaha666** [mattn/gowasmer#3]
I add some code in example like bellow:

```go
package main

import (
	"encoding/json"
	"github.com/mattn/gowasmer/wasmutil"
	"syscall/js"
)

func Add(a, b int) int {
	json.Marshal(123)
	//or time.Now()
	//or fmt.Println()
	return a + b
}

func main() {
	c := make(chan struct{})
	js.Global().Set("Add", js.FuncOf(wasmutil.Wrap(Add)))
	<-c
}
```

When I run the example , it panics:

```
panic: syscall/js: call of Value.Get on undefined

goroutine 1 [running]:
syscall/js.Value.Get({{}, 0x0, 0x0}, {0x22f97, 0x9})
/home/wanghh/workspace/go1.17.7/src/syscall/js/js.go:299 +0xc
syscall.init()
/home/wanghh/workspace/go1.17.7/src/syscall/fs_js.go:21 +0x12

Process finished with the exit code 2
```

So, how do I support 'json.Marshal' 'time.now' 'fmt.xxx' in wasm writen in go ?

**Comment by mattn** [comment]
Please show me the code that I can get the error. (without comments)

**Comment by wahaha666** [comment]
the main function:

```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"

	gowasmer "github.com/mattn/gowasmer"

)

func main() {
	b, err := ioutil.ReadFile("wasm/wasm-example")
	if err != nil {
		log.Fatal(err)
	}

	inst, err := gowasmer.NewInstance(b)
	if err != nil {
		log.Fatal(err)
	}
	
	m := inst.Get("Add")
	r := m.(func([]interface{}) interface{})([]interface{}{1, 3})
	fmt.Printf("1 + 3 = %v\n", r)

}
```

the wasm go code:

```go
package main

import (
	"encoding/json"
	"github.com/mattn/gowasmer/wasmutil"
	"syscall/js"
)

func Add(a, b int) int {
	json.Marshal(123)
	//or time.Now()
	//or fmt.Println()
	return a + b
}


func main() {
	c := make(chan struct{})
	js.Global().Set("Add", js.FuncOf(wasmutil.Wrap(Add)))
	<-c
}

```

**Comment by wahaha666** [comment]
I just want to test some functions of wasm in go, and found that functions such as json.marshal time.Now fmt.Println are not supported in the go code of wasm, why? Can it be solved?Thanks!

**Comment by mattn** [comment]
Yes, you have to use JSON.stringify

```
js.Global().Get("JSON").Call("stringify", 123)
```

**Comment by wahaha666** [comment]
@mattn Thanks for your help!
